### ISSUE TITLE
form delete

### ISSUE THREAD

**Issue by cloud2303** [sairajchouhan/remix-todo#1]
hey bro,i think you shouldn't map form like this , you can use useSubmit hook  to do the delete/finish your todo item;
like this

 let  submit = useSubmit()
![image](https://user-images.githubusercontent.com/78143685/143170852-d6be974a-b3d3-43cc-8d14-10071c63826a.png)
then you can deal with them in the action function
![image](https://user-images.githubusercontent.com/78143685/143170914-fa38c95c-3a31-4bf8-8da4-c17d192f78b4.png)

**Comment by sairajchouhan** [comment]
yes looks good, Thanks for suggestion
